#Настрока базы данных.
mysql:
  #Данные для подключения к базе данных.
  type: MySQL #Не изменять!
  host: hostname #Хост базы данных.
  username: username #Юзер базы данных.
  password: password #Пароль от базы данных.
  database: database #Название базы данных.
  port: 3306 #Порт базы данных.